[package]
name = "gameslog"
version = "0.1.0"
authors = ["ThomasLaPiana"]
edition = "2021"
publish = false

[workspace]
members = [".", "cli", "api", "entity", "migration"]

[dependencies]
gameslog-api = { path = "api" }
