[package]
name = "gameslog"
version = "0.1.0"
authors = ["ThomasLaPiana"]
edition = "2021"
publish = false

default-run = "gameslog"

[workspace]
members = [".", "cli", "api", "entity", "migration"]
default-members = [".", "api", "cli"]

[dependencies]
gameslog-api = { path = "api" }
