
tasks:
  # --- Frontend --- #
  - name: tailwind
    description: "Run tailwind in 'watch' mode"
    command: "pnpm dlx tailwindcss -i styles/tailwind.css -o assets/main.css --watch"

  # --- Database --- #
  - name: createdb
    description: "Create the database"
    command: "sqlx database create"

  - name: migratedb
    description: "Migrate the database"
    command: "sqlx migrate run --source src/migrations"

  # --- Dev --- #
  - name: ws
    description: "Watch the webserver files and reload on changes"
    command: "cargo watch -c -x run"

  - name: check
    command: "cargo check"

  - name: fmt
    command: "cargo fmt"

  - name: test
    command: "cargo test"

  - name: clippy
    command: "cargo clippy -- -D warnings"

pipelines:
  - name: setupdb
    description: "Create and migrate the database"
    tasks: ["createdb", "migratedb"]

  - name: ci
    description: "Run the suite of CI checks, including linting and tests"
    tasks: ["check", "fmt", "test", "clippy"]
